// Simple md parser generated by clauduse std::borrow::Cow;
use std::borrow::Cow;

#[derive(Debug, Clone, PartialEq)]
pub enum Node<'a> {
    Title {
        level: u8,
        text: Cow<'a, str>,
    },
    CodeBlock {
        kind: Option<Cow<'a, str>>,
        content: Cow<'a, str>,
    },
    Text(Cow<'a, str>),
}

impl<'a> Node<'a> {
    /// Convert the node back to markdown
    pub fn to_markdown(&self) -> String {
        match self {
            Node::Title { level, text } => {
                let hashes = "#".repeat(*level as usize);
                format!("{} {}", hashes, text)
            }
            Node::CodeBlock { kind, content } => {
                let lang = kind.as_ref().map(|k| k.as_ref()).unwrap_or("");
                format!("```{}\n{}\n```", lang, content)
            }
            Node::Text(text) => text.to_string(),
        }
    }

    /// Get mutable access to the text content
    pub fn text_mut(&mut self) -> Option<&mut Cow<'a, str>> {
        match self {
            Node::Title { text, .. } => Some(text),
            Node::CodeBlock { content, .. } => Some(content),
            Node::Text(text) => Some(text),
        }
    }

    /// Get mutable access to code block language
    pub fn kind_mut(&mut self) -> Option<&mut Option<Cow<'a, str>>> {
        match self {
            Node::CodeBlock { kind, .. } => Some(kind),
            _ => None,
        }
    }

    /// Set the title level
    pub fn set_level(&mut self, new_level: u8) -> Result<(), &'static str> {
        match self {
            Node::Title { level, .. } => {
                if new_level >= 1 && new_level <= 6 {
                    *level = new_level;
                    Ok(())
                } else {
                    Err("Title level must be between 1 and 6")
                }
            }
            _ => Err("Not a title node"),
        }
    }
}

pub struct Document<'a> {
    pub nodes: Vec<Node<'a>>,
}

impl<'a> Document<'a> {
    pub fn new(nodes: Vec<Node<'a>>) -> Self {
        Self { nodes }
    }

    /// Serialize the document back to markdown
    pub fn to_markdown(&self) -> String {
        let mut output = String::new();

        for (i, node) in self.nodes.iter().enumerate() {
            // Add spacing between nodes
            if i > 0 {
                // Always use double newline to ensure proper separation
                output.push_str("\n\n");
            }

            output.push_str(&node.to_markdown());
        }

        output
    }
}

pub struct Parser<'a> {
    input: &'a str,
    nodes: Vec<Node<'a>>,
}

impl<'a> Parser<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input,
            nodes: Vec::new(),
        }
    }

    pub fn parse(mut self) -> Document<'a> {
        let mut pos = 0;
        let bytes = self.input.as_bytes();

        while pos < bytes.len() {
            // Find start of line
            let line_start = pos;

            // Find end of line
            let mut line_end = pos;
            while line_end < bytes.len() && bytes[line_end] != b'\n' {
                line_end += 1;
            }

            let line = &self.input[line_start..line_end];

            // Skip empty lines
            if line.trim().is_empty() {
                pos = line_end + 1;
                continue;
            }

            // Check for titles
            if let Some(title) = self.parse_title_at(line_start, line_end) {
                self.nodes.push(title);
                pos = line_end + 1;
                continue;
            }

            // Check for code blocks
            if line.starts_with("```") {
                if let Some((block, next_pos)) = self.parse_code_block_at(line_start) {
                    self.nodes.push(block);
                    pos = next_pos;
                    continue;
                }
            }

            // Otherwise it's text - collect consecutive text lines
            if let Some((text, next_pos)) = self.parse_text_at(line_start) {
                self.nodes.push(text);
                pos = next_pos;
                continue;
            }

            pos = line_end + 1;
        }

        Document::new(self.nodes)
    }

    fn parse_title_at(&self, start: usize, end: usize) -> Option<Node<'a>> {
        let line = &self.input[start..end];
        let trimmed = line.trim_start();

        if !trimmed.starts_with('#') {
            return None;
        }

        let level = trimmed.chars().take_while(|&c| c == '#').count();

        if level > 6 || level == 0 {
            return None;
        }

        // Calculate position of text after the hashes
        let trimmed_offset = line.len() - trimmed.len();
        let text_start = start + trimmed_offset + level;
        let text = &self.input[text_start..end].trim();

        Some(Node::Title {
            level: level as u8,
            text: Cow::Borrowed(text),
        })
    }

    fn parse_code_block_at(&self, start: usize) -> Option<(Node<'a>, usize)> {
        let bytes = self.input.as_bytes();
        let first_line_end = self.find_line_end(start);
        let first_line = &self.input[start..first_line_end];

        if !first_line.starts_with("```") {
            return None;
        }

        let kind_str = first_line[3..].trim();
        let kind = if kind_str.is_empty() {
            None
        } else {
            Some(Cow::Borrowed(kind_str))
        };

        // Find the closing ```
        let mut pos = first_line_end + 1;
        let content_start = pos;

        while pos < bytes.len() {
            let line_start = pos;
            let line_end = self.find_line_end(pos);
            let line = &self.input[line_start..line_end];

            if line.starts_with("```") {
                // Found closing
                let content = &self.input[content_start..line_start];
                let content = content.trim_end_matches('\n');

                return Some((
                    Node::CodeBlock {
                        kind,
                        content: Cow::Borrowed(content),
                    },
                    line_end + 1,
                ));
            }

            pos = line_end + 1;
        }

        None // No closing found
    }

    fn parse_text_at(&self, start: usize) -> Option<(Node<'a>, usize)> {
        let bytes = self.input.as_bytes();
        let mut pos = start;
        let text_start = start;
        let mut last_non_empty_end = start;

        while pos < bytes.len() {
            let line_start = pos;
            let line_end = self.find_line_end(pos);
            let line = &self.input[line_start..line_end];

            // Stop at empty lines
            if line.trim().is_empty() {
                break;
            }

            // Stop at titles
            if line.trim_start().starts_with('#') {
                break;
            }

            // Stop at code blocks
            if line.starts_with("```") {
                break;
            }

            last_non_empty_end = line_end;
            pos = line_end + 1;
        }

        if last_non_empty_end > text_start {
            let text = &self.input[text_start..last_non_empty_end];
            Some((Node::Text(Cow::Borrowed(text)), pos))
        } else {
            None
        }
    }

    fn find_line_end(&self, start: usize) -> usize {
        let bytes = self.input.as_bytes();
        let mut pos = start;
        while pos < bytes.len() && bytes[pos] != b'\n' {
            pos += 1;
        }
        pos
    }
}

// Convenience function
pub fn parse(input: &str) -> Document<'_> {
    Parser::new(input).parse()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_and_mutate() {
        let input = "# Title\n\nSome text here.\n\n```rust\nfn main() {}\n```";
        let mut doc = parse(input);

        // Mutate the title
        if let Some(text) = doc.nodes[0].text_mut() {
            *text = Cow::Owned("Modified Title".to_string());
        }

        // Mutate the text
        if let Some(text) = doc.nodes[1].text_mut() {
            text.to_mut().push_str(" And more text!");
        }

        // Change title level
        doc.nodes[0].set_level(2).unwrap();

        let output = doc.to_markdown();
        assert_eq!(
            output,
            "## Modified Title\n\nSome text here. And more text!\n\n```rust\nfn main() {}\n```"
        );
    }

    #[test]
    fn test_roundtrip() {
        let input = r#"# Document

First paragraph.

Second paragraph.

## Section

```python
def hello():
    print("world")
```

Final text."#;

        let doc = parse(input);
        let output = doc.to_markdown();

        // The output should be equivalent (though spacing might differ slightly)
        let doc2 = parse(&output);
        assert_eq!(doc.nodes.len(), doc2.nodes.len());
    }

    #[test]
    fn test_zero_copy_until_mutation() {
        let input = "# Title";
        let mut doc = parse(input);

        // Check that it's still borrowing
        match &doc.nodes[0] {
            Node::Title { text, .. } => {
                assert!(matches!(text, Cow::Borrowed(_)));
            }
            _ => panic!("Expected title"),
        }

        // After mutation, it becomes owned
        if let Some(text) = doc.nodes[0].text_mut() {
            text.to_mut().push('!');
        }

        match &doc.nodes[0] {
            Node::Title { text, .. } => {
                assert!(matches!(text, Cow::Owned(_)));
                assert_eq!(text, "Title!");
            }
            _ => panic!("Expected title"),
        }
    }
}
