// Simple md parser generated by claude

#[derive(Debug, Clone, PartialEq)]
pub enum Node<'a> {
    Title { level: u8, text: &'a str },
    CodeBlock { kind: Option<&'a str>, content: &'a str },
    Text(&'a str),
}

pub struct Parser<'a> {
    input: &'a str,
    nodes: Vec<Node<'a>>,
}

impl<'a> Parser<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input,
            nodes: Vec::new()
        }
    }

    pub fn parse(mut self) -> Vec<Node<'a>> {
        let mut pos = 0;
        let bytes = self.input.as_bytes();

        while pos < bytes.len() {
            // Find start of line
            let line_start = pos;

            // Find end of line
            let mut line_end = pos;
            while line_end < bytes.len() && bytes[line_end] != b'\n' {
                line_end += 1;
            }

            let line = &self.input[line_start..line_end];

            // Skip empty lines
            if line.trim().is_empty() {
                pos = line_end + 1;
                continue;
            }

            // Check for titles
            if let Some(title) = self.parse_title_at(line_start, line_end) {
                self.nodes.push(title);
                pos = line_end + 1;
                continue;
            }

            // Check for code blocks
            if line.starts_with("```") {
                if let Some((block, next_pos)) = self.parse_code_block_at(line_start) {
                    self.nodes.push(block);
                    pos = next_pos;
                    continue;
                }
            }

            // Otherwise it's text - collect consecutive text lines
            if let Some((text, next_pos)) = self.parse_text_at(line_start) {
                self.nodes.push(text);
                pos = next_pos;
                continue;
            }

            pos = line_end + 1;
        }

        self.nodes
    }

    fn parse_title_at(&self, start: usize, end: usize) -> Option<Node<'a>> {
        let line = &self.input[start..end];
        let trimmed = line.trim_start();

        if !trimmed.starts_with('#') {
            return None;
        }

        let level = trimmed.chars().take_while(|&c| c == '#').count();

        if level > 6 || level == 0 {
            return None;
        }

        // Calculate position of text after the hashes
        let trimmed_offset = line.len() - trimmed.len();
        let text_start = start + trimmed_offset + level;
        let text = &self.input[text_start..end].trim();

        Some(Node::Title {
            level: level as u8,
            text,
        })
    }

    fn parse_code_block_at(&self, start: usize) -> Option<(Node<'a>, usize)> {
        let bytes = self.input.as_bytes();
        let first_line_end = self.find_line_end(start);
        let first_line = &self.input[start..first_line_end];

        if !first_line.starts_with("```") {
            return None;
        }

        let kind_str = first_line[3..].trim();
        let kind = if kind_str.is_empty() {
            None
        } else {
            Some(kind_str)
        };

        // Find the closing ```
        let mut pos = first_line_end + 1;
        let content_start = pos;

        while pos < bytes.len() {
            let line_start = pos;
            let line_end = self.find_line_end(pos);
            let line = &self.input[line_start..line_end];

            if line.starts_with("```") {
                // Found closing
                let content = &self.input[content_start..line_start];
                let content = content.trim_end_matches('\n');

                return Some((
                    Node::CodeBlock { kind, content },
                    line_end + 1
                ));
            }

            pos = line_end + 1;
        }

        None // No closing found
    }

    fn parse_text_at(&self, start: usize) -> Option<(Node<'a>, usize)> {
        let bytes = self.input.as_bytes();
        let mut pos = start;
        let text_start = start;
        let mut last_non_empty_end = start;

        while pos < bytes.len() {
            let line_start = pos;
            let line_end = self.find_line_end(pos);
            let line = &self.input[line_start..line_end];

            // Stop at empty lines
            if line.trim().is_empty() {
                break;
            }

            // Stop at titles
            if line.trim_start().starts_with('#') {
                break;
            }

            // Stop at code blocks
            if line.starts_with("```") {
                break;
            }

            last_non_empty_end = line_end;
            pos = line_end + 1;
        }

        if last_non_empty_end > text_start {
            let text = &self.input[text_start..last_non_empty_end];
            Some((Node::Text(text), pos))
        } else {
            None
        }
    }

    fn find_line_end(&self, start: usize) -> usize {
        let bytes = self.input.as_bytes();
        let mut pos = start;
        while pos < bytes.len() && bytes[pos] != b'\n' {
            pos += 1;
        }
        pos
    }
}

// Convenience function
pub fn parse(input: &str) -> Vec<Node<'_>> {
    Parser::new(input).parse()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_titles() {
        let input = r#"# Title 1
## Title 2
### Title 3
#### Title 4
##### Title 5
###### Title 6"#;

        let nodes = parse(input);
        assert_eq!(nodes.len(), 6);

        match &nodes[0] {
            Node::Title { level, text } => {
                assert_eq!(*level, 1);
                assert_eq!(*text, "Title 1");
            }
            _ => panic!("Expected title"),
        }

        match &nodes[5] {
            Node::Title { level, text } => {
                assert_eq!(*level, 6);
                assert_eq!(*text, "Title 6");
            }
            _ => panic!("Expected title"),
        }
    }

    #[test]
    fn test_parse_code_blocks() {
        let input = r#"```rust
fn main() {
    println!("Hello, world!");
}
```

```
plain code block
```"#;

        let nodes = parse(input);
        assert_eq!(nodes.len(), 2);

        match &nodes[0] {
            Node::CodeBlock { kind, content } => {
                assert_eq!(*kind, Some("rust"));
                assert_eq!(*content, "fn main() {\n    println!(\"Hello, world!\");\n}");
            }
            _ => panic!("Expected code block"),
        }

        match &nodes[1] {
            Node::CodeBlock { kind, content } => {
                assert_eq!(*kind, None);
                assert_eq!(*content, "plain code block");
            }
            _ => panic!("Expected code block"),
        }
    }

    #[test]
    fn test_mixed_content() {
        let input = r#"# Test Specification

This is some text that will be parsed.

## Setup

```bash
cargo test
```

### Expected Results

```json
{
    "status": "passed",
    "count": 42
}
```"#;

        let nodes = parse(input);
        assert_eq!(nodes.len(), 6);

        assert!(matches!(nodes[0], Node::Title { level: 1, .. }));
        assert!(matches!(nodes[1], Node::Text(_)));
        assert!(matches!(nodes[2], Node::Title { level: 2, .. }));
        assert!(matches!(nodes[3], Node::CodeBlock { .. }));
        assert!(matches!(nodes[4], Node::Title { level: 3, .. }));
        assert!(matches!(nodes[5], Node::CodeBlock { .. }));

        // Check the text content
        match &nodes[1] {
            Node::Text(text) => {
                assert_eq!(*text, "This is some text that will be parsed.");
            }
            _ => panic!("Expected text node"),
        }
    }

    #[test]
    fn test_no_allocations() {
        let input = "# Title\n```rust\ncode\n```";
        let nodes = parse(input);

        // Verify that text points into the original input
        match &nodes[0] {
            Node::Title { text, .. } => {
                let text_ptr = text.as_ptr();
                let input_ptr = input.as_ptr();
                let input_end = unsafe { input_ptr.add(input.len()) };

                assert!(text_ptr >= input_ptr && text_ptr < input_end);
            }
            _ => panic!("Expected title"),
        }
    }

    #[test]
    fn test_text_parsing() {
        let input = r#"# Document

This is a paragraph
that spans multiple lines
and preserves the original formatting.

Another paragraph after a blank line.

## Section

More text here."#;

        let nodes = parse(input);

        match &nodes[1] {
            Node::Text(text) => {
                assert_eq!(*text, "This is a paragraph\nthat spans multiple lines\nand preserves the original formatting.");
            }
            _ => panic!("Expected text node"),
        }

        match &nodes[2] {
            Node::Text(text) => {
                assert_eq!(*text, "Another paragraph after a blank line.");
            }
            _ => panic!("Expected text node"),
        }
    }
}
