/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_use = 1,
  anon_sym_SEMI = 2,
  anon_sym_func = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_end = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_COLON = 9,
  anon_sym_if = 10,
  anon_sym_then = 11,
  anon_sym_return = 12,
  anon_sym_LT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  sym_identifier = 18,
  sym_number = 19,
  sym_string = 20,
  sym_source_file = 21,
  sym__statement = 22,
  sym_use_stmt = 23,
  sym_function_def = 24,
  sym_param_list = 25,
  sym_param = 26,
  sym_type = 27,
  sym_block = 28,
  sym_if_stmt = 29,
  sym_return_stmt = 30,
  sym_expression_stmt = 31,
  sym_expression = 32,
  sym_binary_expr = 33,
  sym_call = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_param_list_repeat1 = 36,
  aux_sym_call_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_use] = "use",
  [anon_sym_SEMI] = ";",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_return] = "return",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_use_stmt] = "use_stmt",
  [sym_function_def] = "function_def",
  [sym_param_list] = "param_list",
  [sym_param] = "param",
  [sym_type] = "type",
  [sym_block] = "block",
  [sym_if_stmt] = "if_stmt",
  [sym_return_stmt] = "return_stmt",
  [sym_expression_stmt] = "expression_stmt",
  [sym_expression] = "expression",
  [sym_binary_expr] = "binary_expr",
  [sym_call] = "call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_use_stmt] = sym_use_stmt,
  [sym_function_def] = sym_function_def,
  [sym_param_list] = sym_param_list,
  [sym_param] = sym_param,
  [sym_type] = sym_type,
  [sym_block] = sym_block,
  [sym_if_stmt] = sym_if_stmt,
  [sym_return_stmt] = sym_return_stmt,
  [sym_expression_stmt] = sym_expression_stmt,
  [sym_expression] = sym_expression,
  [sym_binary_expr] = sym_binary_expr,
  [sym_call] = sym_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_use_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_function_def] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_return_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 3,
  [8] = 5,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 21,
  [27] = 19,
  [28] = 25,
  [29] = 24,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 37,
  [40] = 34,
  [41] = 35,
  [42] = 32,
  [43] = 38,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 53,
  [57] = 50,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 59,
  [68] = 68,
  [69] = 58,
  [70] = 68,
  [71] = 64,
  [72] = 72,
  [73] = 63,
  [74] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 3,
        '(', 32,
        ')', 34,
        '*', 45,
        '+', 42,
        ',', 33,
        '-', 44,
        '/', 46,
        ':', 35,
        ';', 26,
        '<', 41,
        'e', 13,
        'f', 21,
        'i', 11,
        'r', 8,
        't', 12,
        'u', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ')') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 3,
        '-', 5,
        ';', 26,
        'e', 54,
        'f', 58,
        'i', 51,
        'r', 49,
        'u', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '(', 32,
        ')', 34,
        '*', 45,
        '+', 42,
        ',', 33,
        '-', 43,
        '/', 46,
        ';', 26,
        '<', 41,
        't', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 3,
        ')', 34,
        '*', 45,
        '+', 42,
        ',', 33,
        '-', 43,
        '/', 46,
        ';', 26,
        '<', 41,
        'f', 58,
        'i', 51,
        'r', 49,
        'u', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 22},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 22},
  [40] = {.lex_state = 22},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_function_def] = STATE(2),
    [sym_if_stmt] = STATE(2),
    [sym_return_stmt] = STATE(2),
    [sym_expression_stmt] = STATE(2),
    [sym_expression] = STATE(37),
    [sym_binary_expr] = STATE(13),
    [sym_call] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_func] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_func,
    ACTIONS(9), 1,
      anon_sym_if,
    ACTIONS(11), 1,
      anon_sym_return,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(3), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [39] = 10,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_use,
    ACTIONS(24), 1,
      anon_sym_func,
    ACTIONS(27), 1,
      anon_sym_if,
    ACTIONS(30), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(37), 1,
      sym_expression,
    ACTIONS(36), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(3), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [78] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_use,
    ACTIONS(41), 1,
      anon_sym_func,
    ACTIONS(43), 1,
      anon_sym_end,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(7), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [117] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_use,
    ACTIONS(41), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    STATE(58), 1,
      sym_block,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(4), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [156] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_use,
    ACTIONS(41), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    STATE(59), 1,
      sym_block,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(4), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [195] = 10,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_use,
    ACTIONS(52), 1,
      anon_sym_func,
    ACTIONS(55), 1,
      anon_sym_end,
    ACTIONS(57), 1,
      anon_sym_if,
    ACTIONS(60), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    ACTIONS(36), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(7), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [234] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_use,
    ACTIONS(41), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    STATE(69), 1,
      sym_block,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(4), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [273] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_use,
    ACTIONS(41), 1,
      anon_sym_func,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(47), 1,
      anon_sym_return,
    STATE(39), 1,
      sym_expression,
    STATE(67), 1,
      sym_block,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
    STATE(4), 7,
      sym__statement,
      sym_use_stmt,
      sym_function_def,
      sym_if_stmt,
      sym_return_stmt,
      sym_expression_stmt,
      aux_sym_source_file_repeat1,
  [312] = 2,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [327] = 1,
    ACTIONS(67), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [339] = 1,
    ACTIONS(69), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [351] = 1,
    ACTIONS(63), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [363] = 1,
    ACTIONS(71), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [375] = 2,
    ACTIONS(75), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_number,
      sym_string,
    ACTIONS(73), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [389] = 3,
    ACTIONS(81), 1,
      anon_sym_SEMI,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(79), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [405] = 1,
    ACTIONS(83), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [417] = 3,
    ACTIONS(85), 1,
      anon_sym_SEMI,
    ACTIONS(77), 2,
      sym_number,
      sym_string,
    ACTIONS(79), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [433] = 2,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(89), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [446] = 4,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_call_repeat1,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [463] = 2,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(99), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [476] = 2,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(103), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [489] = 2,
    ACTIONS(101), 2,
      sym_number,
      sym_string,
    ACTIONS(103), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [502] = 2,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(107), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [515] = 2,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      sym_number,
      sym_string,
    ACTIONS(111), 5,
      anon_sym_use,
      anon_sym_func,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [528] = 2,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    ACTIONS(99), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [541] = 2,
    ACTIONS(87), 2,
      sym_number,
      sym_string,
    ACTIONS(89), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [554] = 2,
    ACTIONS(109), 2,
      sym_number,
      sym_string,
    ACTIONS(111), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [567] = 2,
    ACTIONS(105), 2,
      sym_number,
      sym_string,
    ACTIONS(107), 6,
      anon_sym_use,
      anon_sym_func,
      anon_sym_end,
      anon_sym_if,
      anon_sym_return,
      sym_identifier,
  [580] = 2,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [592] = 5,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [610] = 2,
    ACTIONS(119), 1,
      anon_sym_then,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [621] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(30), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [636] = 2,
    ACTIONS(121), 1,
      anon_sym_SEMI,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [647] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(34), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [662] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(12), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [677] = 2,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [688] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [703] = 2,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [714] = 2,
    ACTIONS(127), 1,
      anon_sym_SEMI,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [725] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(40), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [740] = 2,
    ACTIONS(129), 1,
      anon_sym_then,
    ACTIONS(95), 5,
      anon_sym_LT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [751] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(42), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    STATE(13), 2,
      sym_binary_expr,
      sym_call,
  [766] = 3,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    ACTIONS(133), 1,
      sym_identifier,
    STATE(49), 1,
      sym_param,
  [776] = 3,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_call_repeat1,
  [786] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_param_list_repeat1,
  [796] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_param_list_repeat1,
  [806] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_call_repeat1,
  [816] = 3,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_param_list_repeat1,
  [826] = 2,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_param_list,
  [833] = 1,
    ACTIONS(145), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [838] = 1,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [843] = 2,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(9), 1,
      sym_type,
  [850] = 2,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(52), 1,
      sym_type,
  [857] = 2,
    ACTIONS(133), 1,
      sym_identifier,
    STATE(51), 1,
      sym_param,
  [864] = 2,
    ACTIONS(155), 1,
      sym_identifier,
    STATE(6), 1,
      sym_type,
  [871] = 2,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_param_list,
  [878] = 1,
    ACTIONS(157), 1,
      anon_sym_end,
  [882] = 1,
    ACTIONS(159), 1,
      anon_sym_end,
  [886] = 1,
    ACTIONS(161), 1,
      anon_sym_DASH_GT,
  [890] = 1,
    ACTIONS(163), 1,
      anon_sym_DASH_GT,
  [894] = 1,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
  [898] = 1,
    ACTIONS(167), 1,
      anon_sym_DASH_GT,
  [902] = 1,
    ACTIONS(169), 1,
      anon_sym_SEMI,
  [906] = 1,
    ACTIONS(171), 1,
      anon_sym_DASH_GT,
  [910] = 1,
    ACTIONS(173), 1,
      anon_sym_COLON,
  [914] = 1,
    ACTIONS(175), 1,
      anon_sym_end,
  [918] = 1,
    ACTIONS(177), 1,
      sym_identifier,
  [922] = 1,
    ACTIONS(179), 1,
      anon_sym_end,
  [926] = 1,
    ACTIONS(181), 1,
      sym_identifier,
  [930] = 1,
    ACTIONS(183), 1,
      anon_sym_SEMI,
  [934] = 1,
    ACTIONS(185), 1,
      sym_identifier,
  [938] = 1,
    ACTIONS(187), 1,
      anon_sym_DASH_GT,
  [942] = 1,
    ACTIONS(189), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 195,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 273,
  [SMALL_STATE(10)] = 312,
  [SMALL_STATE(11)] = 327,
  [SMALL_STATE(12)] = 339,
  [SMALL_STATE(13)] = 351,
  [SMALL_STATE(14)] = 363,
  [SMALL_STATE(15)] = 375,
  [SMALL_STATE(16)] = 389,
  [SMALL_STATE(17)] = 405,
  [SMALL_STATE(18)] = 417,
  [SMALL_STATE(19)] = 433,
  [SMALL_STATE(20)] = 446,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 476,
  [SMALL_STATE(23)] = 489,
  [SMALL_STATE(24)] = 502,
  [SMALL_STATE(25)] = 515,
  [SMALL_STATE(26)] = 528,
  [SMALL_STATE(27)] = 541,
  [SMALL_STATE(28)] = 554,
  [SMALL_STATE(29)] = 567,
  [SMALL_STATE(30)] = 580,
  [SMALL_STATE(31)] = 592,
  [SMALL_STATE(32)] = 610,
  [SMALL_STATE(33)] = 621,
  [SMALL_STATE(34)] = 636,
  [SMALL_STATE(35)] = 647,
  [SMALL_STATE(36)] = 662,
  [SMALL_STATE(37)] = 677,
  [SMALL_STATE(38)] = 688,
  [SMALL_STATE(39)] = 703,
  [SMALL_STATE(40)] = 714,
  [SMALL_STATE(41)] = 725,
  [SMALL_STATE(42)] = 740,
  [SMALL_STATE(43)] = 751,
  [SMALL_STATE(44)] = 766,
  [SMALL_STATE(45)] = 776,
  [SMALL_STATE(46)] = 786,
  [SMALL_STATE(47)] = 796,
  [SMALL_STATE(48)] = 806,
  [SMALL_STATE(49)] = 816,
  [SMALL_STATE(50)] = 826,
  [SMALL_STATE(51)] = 833,
  [SMALL_STATE(52)] = 838,
  [SMALL_STATE(53)] = 843,
  [SMALL_STATE(54)] = 850,
  [SMALL_STATE(55)] = 857,
  [SMALL_STATE(56)] = 864,
  [SMALL_STATE(57)] = 871,
  [SMALL_STATE(58)] = 878,
  [SMALL_STATE(59)] = 882,
  [SMALL_STATE(60)] = 886,
  [SMALL_STATE(61)] = 890,
  [SMALL_STATE(62)] = 894,
  [SMALL_STATE(63)] = 898,
  [SMALL_STATE(64)] = 902,
  [SMALL_STATE(65)] = 906,
  [SMALL_STATE(66)] = 910,
  [SMALL_STATE(67)] = 914,
  [SMALL_STATE(68)] = 918,
  [SMALL_STATE(69)] = 922,
  [SMALL_STATE(70)] = 926,
  [SMALL_STATE(71)] = 930,
  [SMALL_STATE(72)] = 934,
  [SMALL_STATE(73)] = 938,
  [SMALL_STATE(74)] = 942,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stmt, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_stmt, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_stmt, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_stmt, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_stmt, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_def, 7, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_def, 7, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_stmt, 6, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_stmt, 6, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_newlang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "newlang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
